### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by YingZ000** [kamikazekartik/madrl_traffic_control#3]
Here is my question:
Do you want to compare the results of waiting time?
What factor you changed?
Is this project based on traffic signals time controlling?

**Comment by ksreenivasan** [comment]
Hi @YingZ000,
Yes. The project is indeed based on traffic signal control. We're still working out an approach and we're looking to evaluate based on results of waiting time.

**Comment by YingZ000** [comment]
Thanks for your reply.
